package models.bo;
// Generated Mar 13, 2020 10:12:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private Integer billId;
     private Customer customer;
     private Date date;
     private Set purchases = new HashSet(0);

    public Bill() {
    }

	
    public Bill(Customer customer, Date date) {
        this.customer = customer;
        this.date = date;
    }
    public Bill(Customer customer, Date date, Set purchases) {
       this.customer = customer;
       this.date = date;
       this.purchases = purchases;
    }
   
    public Integer getBillId() {
        return this.billId;
    }
    
    public void setBillId(Integer billId) {
        this.billId = billId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set purchases) {
        this.purchases = purchases;
    }




}


