package models.bo;
// Generated Mar 13, 2020 10:12:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private Category category;
     private String productName;
     private int quantity;
     private double price;
     private Set purchases = new HashSet(0);

    public Product() {
    }

	
    public Product(Category category, String productName, int quantity, double price) {
        this.category = category;
        this.productName = productName;
        this.quantity = quantity;
        this.price = price;
    }
    public Product(Category category, String productName, int quantity, double price, Set purchases) {
       this.category = category;
       this.productName = productName;
       this.quantity = quantity;
       this.price = price;
       this.purchases = purchases;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Set getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set purchases) {
        this.purchases = purchases;
    }

}


